import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { api } from '../services/api';
import LoadingSpinner from '../components/LoadingSpinner';
import './Reports.css';

function Reports() {
  const { t } = useTranslation();
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState({});
  const [elders, setElders] = useState([]);
  const [selectedElder, setSelectedElder] = useState('all');
  const [dateRange, setDateRange] = useState('week');
  const [allTasks, setAllTasks] = useState([]);
  const [allAlerts, setAllAlerts] = useState([]);

  useEffect(() => {
    loadReportData();
  }, []);

  const loadReportData = async () => {
    try {
      setLoading(true);
      const [tasksData, alertsData, eldersData] = await Promise.all([
        api.getTasks(),
        api.getAlerts(),
        api.getElders()
      ]);

      setAllTasks(Array.isArray(tasksData) ? tasksData : []);
      setAllAlerts(Array.isArray(alertsData) ? alertsData : []);
      setElders(Array.isArray(eldersData) ? eldersData : []);

    } catch (error) {
      console.error('Error loading report data:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    calculateStats();
  }, [allTasks, allAlerts, dateRange, selectedElder]);

  const calculateStats = () => {
    const now = new Date();
    const rangeInDays = dateRange === 'week' ? 7 : dateRange === 'month' ? 30 : 90;
    const cutoffDate = new Date(now.setDate(now.getDate() - rangeInDays));

    // Filter Tasks
    const filteredTasks = allTasks.filter(task => {
      const taskDate = new Date(task.created_at || task.dueAt || Date.now());
      const dateMatch = taskDate >= cutoffDate;
      // Note: Assuming task has elderId or similar. If not, filtering by elder might check title/desc
      // For now, we'll try to match exact ID or lenient match
      const elderMatch = selectedElder === 'all' ||
        (task.elderId === selectedElder) ||
        (task.pk && task.pk.includes(selectedElder));
      return dateMatch && elderMatch;
    });

    // Filter Alerts
    const filteredAlerts = allAlerts.filter(alert => {
      const alertDate = new Date(alert.created_at || alert.timestamp || Date.now());
      const dateMatch = alertDate >= cutoffDate;
      const elderMatch = selectedElder === 'all' ||
        (alert.elderId === selectedElder) ||
        (alert.PK && alert.PK.includes(selectedElder));
      return dateMatch && elderMatch;
    });

    setStats({
      totalTasks: filteredTasks.length,
      completedTasks: filteredTasks.filter(t => t.status === 'completed').length,
      pendingTasks: filteredTasks.filter(t => t.status === 'pending').length,
      totalAlerts: filteredAlerts.length,
      urgentAlerts: filteredAlerts.filter(a => a.severity === 'urgent' || a.severity === 'high').length,
      completionRate: filteredTasks.length > 0
        ? Math.round((filteredTasks.filter(t => t.status === 'completed').length / filteredTasks.length) * 100)
        : 0
    });
  };

  const generatePDFReport = () => {
    // Create a printable report
    const reportContent = `
CareCircle Care Report
Generated: ${new Date().toLocaleDateString()}
Period: Last ${dateRange === 'week' ? '7 days' : dateRange === 'month' ? '30 days' : '90 days'}

SUMMARY
-------
Total Tasks: ${stats.totalTasks}
Completed: ${stats.completedTasks}
Pending: ${stats.pendingTasks}
Completion Rate: ${stats.completionRate}%

Total Alerts: ${stats.totalAlerts}
Urgent Alerts: ${stats.urgentAlerts}

This report was generated by CareCircle - AI-Powered Elder Care Platform
    `;

    // Create and download file
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CareCircle-Report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const shareReport = async () => {
    const reportSummary = `CareCircle Care Report (${new Date().toLocaleDateString()}): ${stats.completedTasks}/${stats.totalTasks} tasks completed (${stats.completionRate}%). ${stats.urgentAlerts} urgent alerts.`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'CareCircle Care Report',
          text: reportSummary,
        });
      } catch (error) {
        // User cancelled or share failed - fall back to clipboard
        if (error.name !== 'AbortError') {
          console.log('Share failed, copying to clipboard');
        }
        try {
          await navigator.clipboard.writeText(reportSummary);
          alert('Report summary copied to clipboard!');
        } catch (clipboardError) {
          console.error('Clipboard also failed:', clipboardError);
        }
      }
    } else {
      try {
        await navigator.clipboard.writeText(reportSummary);
        alert('Report summary copied to clipboard!');
      } catch (error) {
        console.error('Clipboard failed:', error);
        alert('Unable to copy. Please copy manually:\n\n' + reportSummary);
      }
    }
  };

  if (loading) {
    return <LoadingSpinner message="Generating reports..." />;
  }

  return (
    <div className="reports-page">
      <div className="page-header">
        <div>
          <h1>📄 Care Reports</h1>
          <p className="subtitle">Generate and share care summaries</p>
        </div>
        <div className="header-actions">
          <button className="btn btn-secondary" onClick={shareReport}>
            📤 Share
          </button>
          <button className="btn btn-primary" onClick={generatePDFReport}>
            📥 Download Report
          </button>
        </div>
      </div>

      {/* Report Filters */}
      <div className="report-filters">
        <div className="filter-group">
          <label>Time Period</label>
          <select
            value={dateRange}
            onChange={(e) => setDateRange(e.target.value)}
          >
            <option value="week">Last 7 Days</option>
            <option value="month">Last 30 Days</option>
            <option value="quarter">Last 90 Days</option>
          </select>
        </div>
        <div className="filter-group">
          <label>Elder</label>
          <select
            value={selectedElder}
            onChange={(e) => setSelectedElder(e.target.value)}
          >
            <option value="all">All Elders</option>
            {elders.map(elder => (
              <option key={elder.id} value={elder.id}>{elder.name}</option>
            ))}
          </select>
        </div>
      </div>

      {/* Report Cards */}
      <div className="report-grid">
        {/* Summary Card */}
        <div className="report-card summary-card">
          <div className="card-header">
            <h3>📊 Care Summary</h3>
          </div>
          <div className="summary-stats">
            <div className="summary-stat">
              <div className="stat-circle success">
                <span className="stat-value">{stats.completionRate}%</span>
              </div>
              <div className="stat-label">Task Completion</div>
            </div>
            <div className="summary-details">
              <div className="detail-row">
                <span>Total Tasks</span>
                <strong>{stats.totalTasks}</strong>
              </div>
              <div className="detail-row">
                <span>Completed</span>
                <strong className="text-success">{stats.completedTasks}</strong>
              </div>
              <div className="detail-row">
                <span>Pending</span>
                <strong className="text-warning">{stats.pendingTasks}</strong>
              </div>
            </div>
          </div>
        </div>

        {/* Alerts Card */}
        <div className="report-card alerts-card">
          <div className="card-header">
            <h3>🚨 Alert Summary</h3>
          </div>
          <div className="alert-summary">
            <div className="alert-stat">
              <div className="alert-number">{stats.totalAlerts}</div>
              <div className="alert-label">Total Alerts</div>
            </div>
            <div className="alert-stat urgent">
              <div className="alert-number">{stats.urgentAlerts}</div>
              <div className="alert-label">Urgent</div>
            </div>
          </div>
        </div>

        {/* Quick Actions Card */}
        <div className="report-card actions-card">
          <div className="card-header">
            <h3>⚡ Quick Export</h3>
          </div>
          <div className="export-options">
            <button className="export-btn" onClick={generatePDFReport}>
              <span className="export-icon">📄</span>
              <span>Text Report</span>
            </button>
            <button className="export-btn" onClick={shareReport}>
              <span className="export-icon">📧</span>
              <span>Email Summary</span>
            </button>
            <button className="export-btn" onClick={() => window.print()}>
              <span className="export-icon">🖨️</span>
              <span>Print Report</span>
            </button>
          </div>
        </div>
      </div>

      {/* Report Preview */}
      <div className="report-preview">
        <div className="preview-header">
          <h3>📋 Report Preview</h3>
          <span className="preview-date">Generated: {new Date().toLocaleDateString()}</span>
        </div>
        <div className="preview-content">
          <div className="preview-section">
            <h4>Care Activity Summary</h4>
            <p>
              During the selected period, your care team completed <strong>{stats.completedTasks}</strong> out
              of <strong>{stats.totalTasks}</strong> tasks, achieving a <strong>{stats.completionRate}%</strong> completion rate.
            </p>
          </div>
          <div className="preview-section">
            <h4>Alert Activity</h4>
            <p>
              The system detected <strong>{stats.totalAlerts}</strong> alerts,
              with <strong>{stats.urgentAlerts}</strong> requiring urgent attention.
            </p>
          </div>
          <div className="preview-section">
            <h4>Recommendations</h4>
            <p>
              {stats.completionRate >= 80
                ? '✅ Excellent care coordination! Keep up the great work.'
                : stats.completionRate >= 50
                  ? '⚠️ Consider reviewing pending tasks to improve completion rate.'
                  : '🚨 Many tasks remain incomplete. Consider redistributing workload among caregivers.'}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Reports;

