/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xQd1jw9nV",
    "aws_user_pools_web_client_id": "3fnpfoqg3f2vevpfqqtt9rqui0",
    "aws_cloud_logic_custom": [
        {
            "name": "CareCircleAPI",
            "endpoint": "http://localhost:3002",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
